### PR TITLE
Version 1.0 BETA

### PR DESCRIPTION
**Pull request by Victorb101**
Created board, schematic, gerbers, bom, and started CAD.

### CODE REVIEW

**Comment by Victorb101** [comment]
@aaronbeekay Review for BETA

**Comment by Victorb101** [comment]
@aaronbeekay Review for Version 1.0?

**Comment by Victorb101** [comment]
@aaronbeekay Good to go

**Comment by aaronbeekay** [comment]
@Victorb101 - the "Cost" column in your BOM should be completely filled out -- I won't block this right now but in the future I may.

Otherwise looking good.

**Pull request merged**
